/*
DEBE RECONOCER:

int y ; String x ;
x = " a + b ";
y = a + b ;

 */
package tareaminianalisislexicosimple;

/**
 *
 * @author majo
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;




public class ventana extends javax.swing.JFrame {
    ArrayList<tokensLexemas> listaTokensLexemas = new ArrayList();
    
    
    
    
    /**
     * Creates new form ventana
     */
    
    
    
    
    public ventana() {
        initComponents();
    }

    //ACCIONES
    //BUSCANDO PALABRA...
    public boolean buscarPalabra(String palabra){
        boolean hallado = false;
        int contador = 0;
        
        while (hallado == false && contador<listaTokensLexemas.size()) {            
            if (listaTokensLexemas.get(contador).getPalabra().compareTo(palabra) == 0) {    //==0 cadenas equivalentes
                hallado = true;
                
            } else {
                contador++;
            }
            
        }//fin while
        
        if (hallado == true) {
            JOptionPane.showMessageDialog(null, "ʕ•́ᴥ•̀ʔっ SE HA ENCONTRADO LA PALABRA \n" + listaTokensLexemas.get(contador).toString());
            return false;
            
        } else {
            JOptionPane.showMessageDialog(null, "ʕ•́ᴥ•̀ʔっ NO SE HA ENCONTRADO LA PALABRA");
            return true;
        }
        
    }//fin buscarPalabra
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaTokenst = new javax.swing.JTextArea();
        btnAnalizarTokens = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TEXTO DE ENTRADA");

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jLabel3.setText("TOKENS");

        txtareaTokenst.setColumns(20);
        txtareaTokenst.setRows(5);
        txtareaTokenst.setEnabled(false);
        jScrollPane2.setViewportView(txtareaTokenst);

        btnAnalizarTokens.setText("ANALIZAR TOKENS");
        btnAnalizarTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarTokensActionPerformed(evt);
            }
        });

        jLabel4.setText("NOTA: INGRESAR SALTO DE LINEA AL FINAL DEL TEXTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnalizarTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAnalizarTokens)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarTokensActionPerformed
        // TODO add your handling code here:
        listaTokensLexemas.clear();//no tocar
        String entrada = this.txtarea.getText(); 
        new Analizador(listaTokensLexemas).analizar(txtarea.getText());
        
        for (int i = 0; i < listaTokensLexemas.size(); i++) {
            txtareaTokenst.setText(txtareaTokenst.getText() + "\n" + listaTokensLexemas.get(i).toString());
        }//fin for
        //btnAnalizarAutomata.setEnabled(true);
        
        
    }//GEN-LAST:event_btnAnalizarTokensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarTokens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextArea txtareaTokenst;
    // End of variables declaration//GEN-END:variables
}
